name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Homebrew
        run: brew install flow-cli
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npx jest
